export const CURRENCY_GET_AVAILABLE = 'USER/GET_AVAILABLE';
export const CURRENCY_GET_CONVERTER = 'USER/GET_CONVERTER';
export const CURRENCY_GET_ONE_TO_ALL = 'USER/GET_ONE_TO_ALL';


export const DASHBOARD_INIT = 'DASHBOARD/INIT';
